apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps
spec:
    selector:
        matchLabels:
            app: ftps
    replicas: 1
    template:
        metadata:
            labels:
                app: ftps
        spec:
            containers:
            - name: ftps
              image: ftps:rde-oliv
              ports:
              - containerPort: 20
              - containerPort: 21
              - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  ports:
  - name: ftps-data
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftps-conn
    port: 21
    protocol: TCP
    targetPort: 21
  - name: passv-mode
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.98
